[package]
name = "aoc2022"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
measure_time = "0.8"
itertools = "0.10.5"
regex = "1"
lazy_static = "1.4.0"
serde_json = "1.0"
evalexpr = "8.1.0"